In [6]:
import numpy as np

# 1. A rank 2 (2D) array that resembles the specified matrix
array_2d = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])

# 2. An array with 4 rows and 3 columns of zeros
array_zeros = np.zeros((4, 3))

# 3. An array of ones with 3 rows and 4 columns
array_ones = np.ones((3, 4))

# 4. An array containing integers 4 to 13 inclusive
array_range = np.arange(4, 14)

# 5. An array containing the floats 0., 1.5, 3., 4.5
array_custom = np.array([0., 1.5, 3., 4.5])

# 6. A 2 by 2 array containing '4' in each position
array_4 = np.full((2, 2), 4)

# 7. (i) Identity matrix of size 4
identity_matrix = np.eye(4)

# (ii) Diagonal matrix with [10, 12] as the diagonals
diagonal_matrix = np.diag([10, 12])

# 8. A 3 by 3 array with random floats in [0, 10]
random_floats = np.random.uniform(0, 10, (3, 3))

# 9. A 3 by 3 array with random integers in [10, 20]
random_integers = np.random.randint(10, 21, (3, 3))

# 1. Slicing Arrays
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# a. Get a subarray of the first row and first 2 columns
subarray_a = myArray[0, :2]

# b. Change all elements in 1st and second row to 0
myArray[:2, :] = 0

# 2. Create an array and reverse the order
reversed_array = np.arange(21)[::-1]

# 3. Reshaping
reshaped_myArray = np.array([[11, 12, 13], [14, 15, 16]]).reshape(3, 2)

# 4. Math
math_myArray = np.arange(10)
squared = np.square(math_myArray)
sqrt = np.sqrt(math_myArray)
multiplied = squared * sqrt

# 5. Adding Elements
adding_myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
adding_myArray = np.vstack([adding_myArray, [20, 21, 22]])
adding_myArray = np.hstack([adding_myArray, [[30], [40], [50], [0]]])

# 6. Inserting Elements
insert_myArray = np.zeros((2, 2))
insert_myArray = np.insert(insert_myArray, 2, 1, axis=1)
insert_myArray = np.vstack([insert_myArray, [2, 2, 2], [2, 2, 2]])
insert_myArray = np.delete(insert_myArray, -1, axis=1)
insert_myArray = np.delete(insert_myArray, -1, axis=0)

# 7. Deleting Elements
delete_myArray = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
delete_myArray = np.delete(delete_myArray, 1, axis=1)

# 8. TEST EXERCISE
exercise_1 = np.arange(10)
exercise_1[exercise_1 % 2 == 1] = -1

exercise_2 = np.arange(9).reshape(3, 3)

exercise_3 = np.arange(4).reshape(2, 2) + 202

exercise_random_ints = np.random.randint(30, 41, 10)

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
greater_positions = np.where(x > y)
equal_positions = np.where(x == y)

exercise_6 = np.arange(100).reshape(5, 20)
first_four_columns = exercise_6[:, :4]

# Printing one of the created arrays as an example
print("2D Array:")
print(array_2d)
print("\nArray of Zeros:")
print(array_zeros)
print("\nArray of Ones:")
print(array_ones)
print("\nArray of Integers 4 to 13:")
print(array_range)
print("\nCustom Float Array:")
print(array_custom)
print("\n2x2 Array with 4s:")
print(array_4)
print("\nIdentity Matrix:")
print(identity_matrix)
print("\nDiagonal Matrix:")
print(diagonal_matrix)
print("\nRandom Floats Array:")
print(random_floats)
print("\nRandom Integers Array:")
print(random_integers)
print("1. Extracted Subarray:", subarray_a)
print("2. Change to 0:\n", myArray)
print("3. Reverse Order:", reversed_array)
print("4. Matrix Reshaped:\n", reshaped_myArray)
print("5. Array with Added New Values:\n", adding_myArray)
print("6. Final Steps for Inserting and Dodo:\n", insert_myArray)
print("7. Test for squares and Sqrt Operations:", squared, sqrt, multiplied)
print("8. First Four Columns of 2-D Array:\n", first_four_columns)


2D Array:
[[11 12 13 14]
 [15 16 17 18]]

Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of Integers 4 to 13:
[ 4  5  6  7  8  9 10 11 12 13]

Custom Float Array:
[0.  1.5 3.  4.5]

2x2 Array with 4s:
[[4 4]
 [4 4]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal Matrix:
[[10  0]
 [ 0 12]]

Random Floats Array:
[[6.7884229  3.40992023 7.65708513]
 [1.67432058 2.72046448 1.69957636]
 [4.85928385 0.20322235 5.47529237]]

Random Integers Array:
[[20 12 19]
 [16 15 20]
 [19 14 20]]
1. Extracted Subarray: [0 0]
2. Change to 0:
 [[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
3. Reverse Order: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
4. Matrix Reshaped:
 [[11 12]
 [13 14]
 [15 16]]
5. Array with Added New Values:
 [[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]
 [20 21 22  0]]
6. Final Steps for Inserting and Dodo:
 [[0. 0.]
 [0. 0.]
 [2. 2.]]
7. Test for 