In [14]:
import numpy as np

# CREATING ARRAYS
# 1. Rank 2 (2D) array resembling the given matrix
array_2d = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])
print("Rank 2 (2D) array:\n", array_2d)

# 2. Array with 4 rows and 3 columns of zeros
zeros_array = np.zeros((4, 3))
print("\nArray with zeros:\n", zeros_array)

# 3. Array of ones with 3 rows and 4 columns
ones_array = np.ones((3, 4))
print("\nArray of ones:\n", ones_array)

# 4. Array of integers 4 to 13 inclusive
range_array = np.arange(4, 14)
print("\nArray of integers 4 to 13:\n", range_array)

# 5. Custom array
custom_array = np.array([0., 1.5, 3., 4.5])
print("\nCustom array:\n", custom_array)

# 6. 2x2 array with 4 in each position
array_4 = np.full((2, 2), 4)
print("\n2x2 array of 4s:\n", array_4)

# 7. i. 4x4 Identity matrix
identity_matrix = np.eye(4)
print("\n4x4 Identity matrix:\n", identity_matrix)

# 7. ii. Diagonal matrix with [10, 12] as the diagonals
diagonal_matrix = np.diag([10, 12])
print("\nDiagonal matrix:\n", diagonal_matrix)

# 8. 3x3 array with random floats in [0, 10]
random_floats_array = np.random.uniform(0, 10, (3, 3))
print("\n3x3 array of random floats in [0, 10]:\n", random_floats_array)

# 9. 3x3 array with random integers in [10, 20]
random_ints_array = np.random.randint(10, 21, (3, 3))
print("\n3x3 array of random integers in [10, 20]:\n", random_ints_array)

# SLICING ARRAYS
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# a. First row and first 2 columns
first_row_first_two_cols = myArray[0, :2]
print("\nFirst row, first 2 columns:\n", first_row_first_two_cols)

# b. Change 1st and 2nd row to 0
myArray[:2, :] = 0
print("\nArray after making the 1st and 2nd row 0:\n", myArray)

# c. Reverse an array [0, 1, 2, ..., 20]
reverse_order_array = np.arange(21)[::-1]
print("\nReverse order array:\n", reverse_order_array)

# d. New reshaped array
reshaped_array = np.array([[11, 12, 13], [14, 15, 16]]).reshape(3, 2)
print("\nReshaped array:\n", reshaped_array)

# MATH

# e. Squares of an array
squares_array = np.arange(10) ** 2
print("\nSquares of each number in the array:\n", squares_array)

# f. Square roots
square_roots_array = np.sqrt(np.arange(10))
print("\nSquare roots of each number in the array:\n", square_roots_array)

# g. Product of the square and its root
product_array = (np.arange(10) ** 2) * np.sqrt(np.arange(10))
print("\nProduct of the square and its root for each number in the array:\n", product_array)

# ADDING ELEMENTS
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# h. New row addition
new_row = np.array([[20, 21, 22]])
myArray_with_new_row = np.vstack((myArray, new_row))
print("\nArray after adding a new row:\n", myArray_with_new_row)

# i. New column addition
new_column = np.array([[30], [40], [50], [60]]).reshape(-1, 1)
myArray_with_new_column = np.hstack((myArray_with_new_row, new_column))
print("\nArray after adding a new column:\n", myArray_with_new_column)

# INSERTING AND DELETING ELEMENTS
# j. Column of 1s to the 2x2 zeros array
zeros_2x2 = np.zeros((2, 2))
ones_column_added = np.insert(zeros_2x2, 2, 1, axis=1)
print("\nZeros array with a column of 1s:\n", ones_column_added)

# k. 2 rows of 2s to the modified array
rows_of_twos_added = np.insert(ones_column_added, 2, 2, axis=0)
rows_of_twos_added = np.insert(rows_of_twos_added, 2, 2, axis=0)
print("\nArray after adding 2 rows of 2s:\n", rows_of_twos_added)

# l. 3. Remove the last column
modified_array = np.delete(rows_of_twos_added, -1, axis=1)
print("\nAfter removing the last column:\n", modified_array)

# m. 4. Remove the last row
modified_array = np.delete(modified_array, -1, axis=0)
print("\nAfter removing the last row:\n", modified_array)

# DELETING MIDDLE COLUMN
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
myArray_without_middle_column = np.delete(myArray, 1, axis=1)
print("\nArray after removing the middle column:\n", myArray_without_middle_column)

# TEST 1: Replace all odd numbers with -1
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 == 1] = -1
print("\nReplace all odd numbers with -1:\n", exercise_1)

# TEST 2: Convert a 1-D array into a 2-D array with 3 rows
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
exercise_2_reshaped = exercise_2.reshape(3, 3)
print("\n1-D to 2-D with 3 rows:\n", exercise_2_reshaped)

# TEST 3: Add 202 to all elements
exercise_3 = np.arange(4).reshape(2, -1) + 202
print("\nAdding 202 to all elements:\n", exercise_3)

# Generating a 1-D array of 10 random integers between 30 and 40
random_integers = np.random.randint(30, 41, 10)
print("\n1-D array of 10 random integers between 30 and 40:\n", random_integers)

# Find the comparison results
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
positions_more_than = np.where(x > y)
positions_equal_to = np.where(x == y)
print("\nPositions where x is more than y:\n", positions_more_than)
print("Positions where x is equal to y:\n", positions_equal_to)

# Slicing to get first four columns of a 2-D 5x20 array
exercise_6 = np.arange(100).reshape(5, -1)
first_four_columns = exercise_6[:, :4]
print("\n2-D array first four columns:\n", first_four_columns)


Rank 2 (2D) array:
 [[11 12 13 14]
 [15 16 17 18]]

Array with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of integers 4 to 13:
 [ 4  5  6  7  8  9 10 11 12 13]

Custom array:
 [0.  1.5 3.  4.5]

2x2 array of 4s:
 [[4 4]
 [4 4]]

4x4 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Diagonal matrix:
 [[10  0]
 [ 0 12]]

3x3 array of random floats in [0, 10]:
 [[9.67382812 8.96960878 4.62577358]
 [2.53942921 1.96624143 9.6018886 ]
 [1.96443162 0.47308363 9.2680774 ]]

3x3 array of random integers in [10, 20]:
 [[15 14 15]
 [13 14 13]
 [14 17 18]]

First row, first 2 columns:
 [11 12]

Array after making the 1st and 2nd row 0:
 [[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]

Reverse order array:
 [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

Reshaped array:
 [[11 12]
 [13 14]
 [15 16]]

Squares of each number in the array:
 [ 0  1  4  9 16 25 36 49 64 81]

Square roo